<a href="https://colab.research.google.com/github/Darianath/CSVD/blob/main/%D0%9B%D0%A01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Була присутня на парі

In [ ]:
import numpy as np

np.__version__


'2.0.2'

In [ ]:
ve = np.array([5, 8, 3, 2, 4], dtype = float)
ve

array([5., 8., 3., 2., 4.])

In [ ]:
ve[0]

np.float64(5.0)

In [ ]:
a = np.array([[6, 9, 4],
              [2, 8, 8]])
a

array([[6, 9, 4],
       [2, 8, 8]])

In [ ]:
a[1, 2]

np.int64(8)

In [ ]:
a[0,0]

np.int64(6)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size

6

In [ ]:
a.shape

(2, 3)

In [ ]:
b = np.array([[4, 6, 1], [4, 8, 3], [6, 2, 5]])
b

array([[4, 6, 1],
       [4, 8, 3],
       [6, 2, 5]])

In [ ]:
c = np.matrix([[5, 3, 6], [4, 5, 8], [3, 7, 9]])
c

matrix([[5, 3, 6],
        [4, 5, 8],
        [3, 7, 9]])

In [ ]:
diag_b = np.diag(b)
diag_b

array([4, 8, 5])

In [ ]:
b_diag = np.diag(diag_b)

b_diag

array([[4, 0, 0],
       [0, 8, 0],
       [0, 0, 5]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.random.randint(11, size=(4,4))

array([[2, 5, 7, 3],
       [3, 2, 7, 7],
       [6, 0, 7, 8],
       [8, 0, 6, 7]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [ ]:
b = np.array([[4, 6, 1], [4, 8, 3], [6, 2, 5]])
b

array([[4, 6, 1],
       [4, 8, 3],
       [6, 2, 5]])

In [ ]:
b.transpose()

array([[4, 4, 6],
       [6, 8, 2],
       [1, 3, 5]])

In [ ]:
b.T

array([[4, 4, 6],
       [6, 8, 2],
       [1, 3, 5]])

In [ ]:
d = np.array([[7, 5], [8, 2]])
d

array([[7, 5],
       [8, 2]])

In [ ]:
d_det = np.linalg.det(d)
d_det.round(2)

np.float64(-26.0)

In [ ]:
a = np.matrix([[4, 2, 5], [8, 5, 9]])
b = 3 * a
b

matrix([[12,  6, 15],
        [24, 15, 27]])

In [ ]:
a = np.matrix([[1, 3], [7, 5]])
b = np.matrix([[2, 8], [6, 1]])
c = np.dot(a, b)
c

matrix([[20, 11],
        [44, 61]])

In [ ]:
np.multiply(a, b)

matrix([[ 2, 24],
        [42,  5]])

In [ ]:
a/b

matrix([[0.5       , 0.375     ],
        [1.16666667, 5.        ]])

In [ ]:
np.divide(a, b)

matrix([[0.5       , 0.375     ],
        [1.16666667, 5.        ]])

In [ ]:
a = np.matrix([[8, -2], [5, 6]])

a_inv = np.linalg.inv(a)
a_inv

matrix([[ 0.10344828,  0.03448276],
        [-0.0862069 ,  0.13793103]])

In [ ]:
rank = np.linalg.matrix_rank(a)
rank

np.int64(2)

In [ ]:
a = np.array([[0, -2, 2],
              [-4,  0, 2],
              [0, 2, 0]])


e, w = np.linalg.eig(a)

In [ ]:
e

array([-4.        ,  1.99999997,  2.00000003])

In [ ]:
w

array([[-5.57086015e-01,  1.11219577e-08, -1.11219579e-08],
       [-7.42781353e-01,  7.07106776e-01,  7.07106787e-01],
       [ 3.71390676e-01,  7.07106787e-01,  7.07106776e-01]])